name: 'telegram_data_warehouse' # Project name
version: '1.0.0'
config-version: 2

profile: 'telegram_data_warehouse' # Link to your profile in profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory to store compiled SQL files
clean-targets:         # directories to clean out on `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

# Configure models
models:
  telegram_data_warehouse:
    # This will set the materialization for all models in this project to 'view' by default
    +materialized: view
    staging:
      # For staging models, we typically use views
      +materialized: view
    marts:
      # For final mart tables, we often use tables or incremental tables
      +materialized: table